import Head from 'next/head'
import Image from 'next/image'
// import Video from 'next/video'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
// import Image from "next/image"
import deved from '../../public/dev-ed-wave.png'
import abhiport from '../../public/AbhishekPortfolio.png'
import react_1 from '../../public/react-1.png'
import python from '../../public/Python.png'
import database from '../../public/database.png'
import crypto_hunter from '../../public/crypto-hunter.png'
import Link from 'next/link';
import weather from '../../public/weather.png'
import restaurant from '../../public/Restaurant.png'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Abhishek Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
    <section className="min-h-screen">
    <nav className="py-5 flex justify-between">
      <h1 className="text-xl font-burtons dark:text-gray-400">
        Abhishek Kalhan
      </h1>
      <ul className="flex items-center">
        <li>
          <BsFillMoonStarsFill onClick={() => {setDarkMode(!darkMode)}} className="cursor-pointer text-2xl"/>
        </li>
        <li>
          <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 dark:text-black" href="https://www.linkedin.com/in/abhishek-kalhan/">LinkedIn</a>
        </li>
      </ul>
    </nav>
      <div className="text-center p-10 ">
        <h2 className="text-5xl py-2 text-teal-500 font-medium md:text-6xl ">Abhishek Kalhan</h2>
        <h3 className="text-2xl py-2 md:text-3xl dark:text-teal-600">FullStack Web Developer</h3>
        <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-400">
          As a seasoned full stack web developer, I possess expertise in developing both front-end 
          and back-end services, and specialize in creating dynamic web applications that 
          deliver exceptional user experiences while meeting business objectives.
        </p>
      </div>
      <div className="relative mx-auto bg-gradient-to-b from-gray-600 rounded-full w-80 h-80 mt-5 overflow-hidden md:h-96 md:w-96">
        <Image src={abhiport}  objectFit="cover"/>
      </div>
    </section>
      <section>
        <div>
          <h3 className="text-3xl dark:text-teal-500">Overview</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">As a highly skilled <span className="text-teal-600"> Full Stack Web Developer</span>, 
          I have a proven track record of designing and developing robust, scalable, and user-friendly web applications. 
          With <span className="text-teal-600"> 3.5 years</span> of experience in the field, 
          I possess in-depth knowledge of various programming languages, frameworks, and tools required to build 
          dynamic web solutions from scratch. I am passionate about leveraging my technical skills to create 
          <span className="text-teal-600"> cutting-edge applications</span> that meet the specific needs of businesses and end-users. 
          With a <span className="text-teal-600"> keen eye for detail</span> and a collaborative approach to work, I am confident in my ability 
          to deliver <span className="text-teal-600"> quality results on time</span> and within budget</p>
        </div>
      
      <div className="lg:flex gap-10">
        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-600">
          <Image src={react_1} width={100} height={100}/>
          <h3 className="text-lg font-medium pt-8 pb-2">React</h3>
          <p className="py-2">
          Proficient in using React to develop high-performance, scalable, and maintainable web applications,
           and have a deep understanding of React's core concepts and libraries.
          </p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-600">
          <Image src={python} width={100} height={100}/>
          <h3 className="text-lg font-medium pt-8 pb-2">Python</h3>
          <p className="py-2">
          As a Python expert, am well-versed in the language's core concepts, syntax, and standard libraries,
           and am comfortable working with popular frameworks and tools such as Flask, Django, NumPy, and Pandas.
          </p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-600">
          <Image src={database} width={100} height={100}/>
          <h3 className="text-lg font-medium pt-8 pb-2">Database</h3>
          <p className="py-2">
          Have extensive experience working with a wide range of database systems, 
          including relational databases such as MySQL and PostgreSQL, as well as NoSQL databases such as MongoDB.
          </p>
          </div>
      </div>
      </section>
      <section>
        <div>
          <h3 className="text-3xl py-1 dark:text-teal-500">Portfolio</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">Throughout my 
          <span className="text-teal-600"> software development journey</span>, 
          I have had the opportunity to work with several startups and collaborate with talented individuals to 
          create websites for both business and consumer use. Here are some examples of my
           past projects to <span className="text-teal-600"> highlight my experience</span> and expertise in this field:</p>
        </div>
        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/3 flex-1">
          <Link href="https://restaurant-4xghrng1v-abhishek-kalhan.vercel.app/menu.html">
              <div className="image-container">
                <Image src={restaurant} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
                <div className="overlay">
                  <p>Visit site</p>
                </div>
              </div>
            </Link>
            </div>
            <div className="basis-1/3 flex-1">
            <Link href="https://weather-qsd27kssa-abhishek-kalhan.vercel.app">
              <div className="image-container">
                <Image src={weather} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
                <div className="overlay">
                  <p>Visit site</p>
                </div>
              </div>
            </Link>
            </div>
            <div className="basis-1/3 flex-1">
            
            <Link href="https://crypto-hunter-rthv.vercel.app">
              <div className="image-container">
                <Image src={crypto_hunter} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
                <div className="overlay">
                  <p>Visit site</p>
                </div>
              </div>
            </Link>
            </div>
        </div>
      </section>
      
      </main>
    </div>
  )
}
